<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.tahopen</groupId>
    <artifactId>tahopen-ce-jar-parent-pom</artifactId>
    <version>0.1.0.0</version>
  </parent>

  <groupId>org.tahopen</groupId>
  <artifactId>simple-jndi</artifactId>
  <version>0.1.0.0</version>

  <name>Simple JNDI with bug fixes</name>
  <distributionManagement>

  </distributionManagement>
  <properties>
    <junit.version>4.11</junit.version>
    <mockito.version>3.12.4</mockito.version>

    <commons-lang.version>2.6</commons-lang.version>
    <commons-dbcp2.version>2.9.0</commons-dbcp2.version>
    <commons-pool2.version>2.11.1</commons-pool2.version>
    <encryption-support.version>0.1.0.0</encryption-support.version>
    <maven-surefire-plugin.version>2.21.0</maven-surefire-plugin.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>commons-lang</groupId>
      <artifactId>commons-lang</artifactId>
      <version>${commons-lang.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-dbcp2</artifactId>
      <version>${commons-dbcp2.version}</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>${mockito.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.tahopen</groupId>
      <artifactId>tahopen-encryption-support</artifactId>
      <version>${encryption-support.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-pool2</artifactId>
      <version>${commons-pool2.version}</version>
    </dependency>
  </dependencies>
</project>
